spring:
  application:
    name: platform-sse
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE:}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        group: ${NACOS_DISCOVERY_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR}
        namespace: ${NACOS_NAMESPACE:}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
        group: ${NACOS_CONFIG_GROUP}
  config:
    import:
      - nacos:application.yml?group=${NACOS_CONFIG_GROUP}
      - nacos:${spring.application.name}.yml?group=${NACOS_CONFIG_GROUP}
